# Generated by Django 3.0.5 on 2020-05-16 01:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_auto_20200515_2031'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolios',
            name='created_date',
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='portfolios',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='portfolios',
            name='image',
            field=models.ImageField(default='', upload_to='images'),
        ),
        migrations.AddField(
            model_name='portfolios',
            name='order',
            field=models.IntegerField(default=0),
        ),
    ]
