# Generated by Django 3.0.5 on 2020-05-17 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_auto_20200517_1436'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolios',
            name='features',
            field=models.TextField(default=''),
        ),
    ]
