# Generated by Django 3.0.5 on 2020-05-04 20:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Static_Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=254)),
                ('url', models.CharField(default='', max_length=254, unique=True)),
                ('content', models.TextField()),
                ('created_date', models.DateField(default=datetime.datetime.now)),
                ('updated_date', models.DateField(default='')),
            ],
            options={
                'verbose_name': 'Page',
                'verbose_name_plural': 'Pages',
            },
        ),
    ]
