# Generated by Django 3.0.5 on 2020-05-10 14:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('static_content', '0001_initial'), ('static_content', '0002_auto_20200504_2150'), ('static_content', '0003_auto_20200504_2211'), ('static_content', '0004_auto_20200507_2020'), ('static_content', '0005_static_page_order'), ('static_content', '0006_auto_20200509_0845')]

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Static_Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=254)),
                ('url', models.CharField(default='', max_length=254, unique=True)),
                ('content', models.TextField()),
                ('created_date', models.DateField(default=datetime.datetime.now)),
                ('updated_date', models.DateField(default=datetime.datetime.now)),
                ('header', models.CharField(blank=True, default='', max_length=254, null=True)),
                ('title', models.CharField(default='', max_length=254, null=True)),
                ('onmenu', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=3)),
                ('published', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=3)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Page',
                'verbose_name_plural': 'Pages',
            },
        ),
    ]
