# Generated by Django 3.0.5 on 2020-05-04 20:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('static_content', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='static_page',
            name='updated_date',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
