# Generated by Django 3.0.5 on 2020-05-04 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('static_content', '0002_auto_20200504_2150'),
    ]

    operations = [
        migrations.AddField(
            model_name='static_page',
            name='header',
            field=models.CharField(default='', max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='static_page',
            name='title',
            field=models.CharField(default='', max_length=254, null=True),
        ),
    ]
