# Generated by Django 3.0.5 on 2020-05-07 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('static_content', '0003_auto_20200504_2211'),
    ]

    operations = [
        migrations.AddField(
            model_name='static_page',
            name='onmenu',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=3),
        ),
        migrations.AddField(
            model_name='static_page',
            name='published',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=3),
        ),
    ]
