# Generated by Django 3.0.5 on 2020-05-08 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('static_content', '0004_auto_20200507_2020'),
    ]

    operations = [
        migrations.AddField(
            model_name='static_page',
            name='order',
            field=models.IntegerField(default=0),
        ),
    ]
