# Generated by Django 3.0.5 on 2020-05-09 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('static_content', '0005_static_page_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='static_page',
            name='header',
            field=models.CharField(blank=True, default='', max_length=254, null=True),
        ),
    ]
